ALTER TABLE MARK DROP CONSTRAINT mark_student_id_fkey;
ALTER TABLE MARK DROP CONSTRAINT  mark_subject_id_fkey;
ALTER TABLE MARK ADD CONSTRAINT mark_student_id_fkey  FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID) ON DELETE CASCADE;
ALTER TABLE MARK ADD CONSTRAINT mark_subject_id_fkey  FOREIGN KEY(SUBJECT_ID) REFERENCES SUBJECT(ID)  ON DELETE CASCADE;
ALTER TABLE PAYMENT DROP CONSTRAINT payment_type_id_fkey;
ALTER TABLE PAYMENT DROP CONSTRAINT payment_student_id_fkey;
ALTER TABLE PAYMENT ADD CONSTRAINT payment_student_id_fkey FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID) ON DELETE CASCADE;
ALTER TABLE PAYMENT ADD CONSTRAINT payment_type_id_fkey FOREIGN KEY(TYPE_ID) REFERENCES PAYMENTTYPE(ID)  ON DELETE CASCADE;