SELECT BIRTHDAY  FROM STUDENT ORDER BY BIRTHDAY DESC LIMIT 1;
SELECT PAYMENT_DATE FROM PAYMENT ORDER BY PAYMENT_DATE ASC LIMIT 1;
SELECT AVG(MARK) FROM MARK LEFT JOIN SUBJECT ON MARK.SUBJECT_ID = SUBJECT.ID WHERE SUBJECT.NAME = 'Math';
SELECT MIN(AMOUNT) FROM PAYMENT LEFT JOIN PAYMENTTYPE ON PAYMENT.TYPE_ID = PAYMENTTYPE.ID WHERE PAYMENTTYPE.NAME = 'WEEKLY';